---
- name: Ensure rename architectures
  ansible.builtin.set_fact:
    arch: "{{ gatewayproxy_arch_map[ansible_architecture].rename }}"

- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Ensure additional dependencies are installed (on Ubuntu < 20.04 and any other systems).
  ansible.builtin.apt:
    name: gnupg2
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')

- name: Ensure additional dependencies are installed (on Ubuntu >= 20.04).
  ansible.builtin.apt:
    name: gnupg
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_version is version('20.04', '>=')

- name: Add Gateway Proxy apt key.
  ansible.builtin.apt_key:
    url: "{{ gatewayproxy_apt_gpg_key }}"
    id: "{{ gatewayproxy_repo_key_id }}"
    state: present
    keyring: /usr/share/keyrings/ethersphere-archive-keyring.gpg
  register: add_repository_key
  ignore_errors: "{{ gatewayproxy_apt_ignore_key_error }}"

- name: Ensure curl is present (on older systems without SNI).
  ansible.builtin.package: name=curl state=present
  when: add_repository_key is failed

- name: Add Gateway Proxy apt key (alternative for older systems without SNI).
  ansible.builtin.shell: >
    curl -fsSL {{ gatewayproxy_apt_gpg_key }} | gpg --dearmor -o /usr/share/keyrings/ethersphere-archive-keyring.gpg
  args:
    warn: false
  when: add_repository_key is failed

- name: Add Gateway Proxy repository.
  ansible.builtin.apt_repository:
    repo: "{{ gatewayproxy_apt_repository }}"
    filename: ethersphere
    state: present
    update_cache: true
